spring.application.name=flowmatic

spring.datasource.url=jdbc:postgresql://localhost:5432/flowmatic
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update 

spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

unsplash.access-key=${UNSPLASH_ACCESS_KEY}
